### PR TITLE
Replace gen.coroutine with async

### PR DESCRIPTION
**Pull request by consideRatio**
Supposed to be merged after #3 as it contains it and the gen.coroutine -> async transition.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks, @consideRatio! Can you set a minimum python version in setup.py as well?

I've added you to this repo and will add you shortly to pip :)

**Comment by consideRatio** [comment]
Thanks @yuvipanda, done!

**Comment by yuvipanda** [comment]
Thanks, @consideRatio :) Do you think you can make a release? :D

**Comment by consideRatio** [comment]
@yuvipanda yepp, but what version? 0.2.0? 1.0.0? 0.2? 1.0?

**Comment by yuvipanda** [comment]
@consideRatio Let's go with 1.0 since we have a version pin now.

**Comment by consideRatio** [comment]
@yuvipanda deal, released 1.0 to PyPI which has a major outage so it still sais 0.1 on https://pypi.org/project/jupyterhub-hmacauthenticator/, but pip install gives the right version.

**Comment by yuvipanda** [comment]
Thanks a lot, @consideRatio!

**Comment by consideRatio** [comment]
Likewise @yuvipanda :heart:

**Pull request merged**
